# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(546, 266)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(30, 70, 481, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_absolute_move = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.btn_absolute_move.setObjectName("btn_absolute_move")
        self.horizontalLayout.addWidget(self.btn_absolute_move)
        self.lineEdit_position = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEdit_position.setText("")
        self.lineEdit_position.setObjectName("lineEdit_position")
        self.horizontalLayout.addWidget(self.lineEdit_position)
        self.btn_relative_move = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.btn_relative_move.setObjectName("btn_relative_move")
        self.horizontalLayout.addWidget(self.btn_relative_move)
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(30, 120, 481, 41))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.btn_default_speed = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.btn_default_speed.setObjectName("btn_default_speed")
        self.horizontalLayout_3.addWidget(self.btn_default_speed)
        self.lineEdit_speed = QtWidgets.QLineEdit(self.horizontalLayoutWidget_3)
        self.lineEdit_speed.setText("")
        self.lineEdit_speed.setObjectName("lineEdit_speed")
        self.horizontalLayout_3.addWidget(self.lineEdit_speed)
        self.btn_set_speed = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.btn_set_speed.setObjectName("btn_set_speed")
        self.horizontalLayout_3.addWidget(self.btn_set_speed)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(30, 20, 481, 41))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btn_home = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.btn_home.setObjectName("btn_home")
        self.horizontalLayout_2.addWidget(self.btn_home)
        self.btn_reset = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.btn_reset.setObjectName("btn_reset")
        self.horizontalLayout_2.addWidget(self.btn_reset)
        self.btn_position = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.btn_position.setFont(font)
        self.btn_position.setObjectName("btn_position")
        self.horizontalLayout_2.addWidget(self.btn_position)
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(30, 170, 481, 41))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.btn_connect = QtWidgets.QPushButton(self.horizontalLayoutWidget_4)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btn_connect.setFont(font)
        self.btn_connect.setObjectName("btn_connect")
        self.horizontalLayout_4.addWidget(self.btn_connect)
        self.btn_disconnect = QtWidgets.QPushButton(self.horizontalLayoutWidget_4)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btn_disconnect.setFont(font)
        self.btn_disconnect.setObjectName("btn_disconnect")
        self.horizontalLayout_4.addWidget(self.btn_disconnect)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 546, 20))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Slim9Controller"))
        self.btn_absolute_move.setText(_translate("MainWindow", "Absolute Move"))
        self.lineEdit_position.setPlaceholderText(_translate("MainWindow", "(related position; unit: mm)"))
        self.btn_relative_move.setText(_translate("MainWindow", "Relative Move"))
        self.btn_default_speed.setText(_translate("MainWindow", "Default speed"))
        self.lineEdit_speed.setPlaceholderText(_translate("MainWindow", "(speed; unit: RPS)"))
        self.btn_set_speed.setText(_translate("MainWindow", "Set speed"))
        self.btn_home.setText(_translate("MainWindow", "Initialization"))
        self.btn_reset.setText(_translate("MainWindow", "Reset"))
        self.btn_position.setText(_translate("MainWindow", "Current Position"))
        self.btn_connect.setText(_translate("MainWindow", "Connect"))
        self.btn_disconnect.setText(_translate("MainWindow", "Disconnect"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
